// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDM34Kdy-6qoDTAnZHubeP8wnLpxhVHwo',
    appId: '1:43776677831:web:92a1d015236db33795abe2',
    messagingSenderId: '43776677831',
    projectId: 'mo-sapp',
    authDomain: 'mo-sapp.firebaseapp.com',
    storageBucket: 'mo-sapp.firebasestorage.app',
    measurementId: 'G-CWLF3X50ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQF55pYwYzI6EmJVjbNj5Z3TVXhGGsoI',
    appId: '1:43776677831:android:ab4275120448c63895abe2',
    messagingSenderId: '43776677831',
    projectId: 'mo-sapp',
    storageBucket: 'mo-sapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMI8OAQ1W3CCNB9gqGNNdusTjGj8eSbPU',
    appId: '1:43776677831:ios:0d93f29a7d88420195abe2',
    messagingSenderId: '43776677831',
    projectId: 'mo-sapp',
    storageBucket: 'mo-sapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMI8OAQ1W3CCNB9gqGNNdusTjGj8eSbPU',
    appId: '1:43776677831:ios:0d93f29a7d88420195abe2',
    messagingSenderId: '43776677831',
    projectId: 'mo-sapp',
    storageBucket: 'mo-sapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDM34Kdy-6qoDTAnZHubeP8wnLpxhVHwo',
    appId: '1:43776677831:web:9d706d500b338e6195abe2',
    messagingSenderId: '43776677831',
    projectId: 'mo-sapp',
    authDomain: 'mo-sapp.firebaseapp.com',
    storageBucket: 'mo-sapp.firebasestorage.app',
    measurementId: 'G-T4S7214MS2',
  );
}
